In [1]:
import json
import ijson
import csv
import pandas as pd
from pathlib import Path
pd.options.display.float_format = '{:,}'.format

**Specify your directory here:**

In [2]:
DIR = Path.cwd().parent / 'data'

**This function will calculate the number of records in the input file**

In [3]:
def count_objects(file_name):
    print('counting file:', file_name.name)
    count = 0
    with open(file_name, 'r', encoding='utf-8') as f:
        for _ in ijson.items(f, '', multiple_values=True):
            count += 1
    return count

**Calculate basic statistics of the book graph**

In [4]:
n_book = count_objects(DIR / 'goodreads_books.json')
n_work = count_objects(DIR / 'goodreads_book_works.json')
n_author = count_objects(DIR / 'goodreads_book_authors.json')
n_series = count_objects(DIR / 'goodreads_book_series.json')

counting file: goodreads_books.json
counting file: goodreads_book_works.json
counting file: goodreads_book_authors.json
counting file: goodreads_book_series.json

In [5]:
df_book_stats = pd.DataFrame([n_book, n_work, n_author, n_series], dtype = float, 
                             columns = ['count'],
                             index = ['# book', '# work', '# author', '# series'])
display(df_book_stats)

               count
# book   2,360,655.0
# work   1,521,962.0
# author   829,529.0
# series   400,390.0

**This function will extract statistics from interaction files**

In [6]:
def count_interactions(file_name):
    print('counting file:', file_name.name)
    n_shelve, n_read, n_rate, n_review = 0, 0, 0, 0
    user_set = set()
    with open(file_name) as fin:
        for d in csv.DictReader(fin):
            n_shelve += 1
            n_read += int(d['is_read'])
            n_rate += int(d['rating']) > 0
            n_review += int(d['is_reviewed'])
            user_set.add(d['user_id'])
    return n_shelve, n_read, n_rate, n_review, len(user_set)

In [7]:
n_shelve, n_read, n_rate, n_review, n_user = count_interactions(DIR / 'goodreads_interactions.csv')

counting file: goodreads_interactions.csv

In [8]:
df_interations_stats = pd.DataFrame([n_shelve, n_read, n_rate, n_review, n_user], dtype = float, 
                                    columns = ['count'],
                                    index = ['# shelve', '# read', '# rate', '# review', '# user'])
display(df_interations_stats)

                 count
# shelve 228,648,342.0
# read   112,131,203.0
# rate   104,551,549.0
# review  16,219,149.0
# user       876,145.0